### ISSUE TITLE
Provide a default Site Type for each account

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#11]
At present, WCBS recorders need to change the Site Type each time they return to a page.

Could we allow each user account to set a default Site/Location Type, so that when they go to any relevant page the default view is relevant to their interests. (eg. My Sites, My Walks, Annual Summary, also Branch Sites and Branch Walks for WCBS champions).

**Comment by Gary-van-Breda** [comment]
At the moment the report grid based forms (My sites, Branch Sites, Visit Summary, and All sites) have the ability to store the parameters in a site wide cookie. I have set this up on Live as a trial. This means that when a user chooses WCBS-BBS as the site type in one of these pages, when they visit the other pages, the site type will be default to WCBS-BBS automatically, until they change it. Is this an acceptable solution, rather than having a user specified default?
The other forms would need to be updated to be able to use the same cookie to track their parameters.

**Comment by DavidRoy** [comment]
Yes, good option. Thanks

**Comment by IanMiddlebrook** [comment]
Yes, good option.
If this could also be applied to 'My Walks', 'Branch Walks' and 'Annual Summary' - that would be ideal.
Many thanks,
Ian

**Comment by Gary-van-Breda** [comment]
This has been applies to all pages on the D7 site.
