### ISSUE TITLE
Cannot edit user passwords

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#115]
Hi I cannot get to the page to edit the user password. There have been issues all over the weekend about people not being able to log in and Ian and I have been inundated with emails.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you look at the server logs? I'm getting a 500 internal server error (on this and the annual summary page #116), and can't see anything else of use!

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I looked at server log and there is not any single information logged regarding this. 

When I looked at firefox's , I found this error "The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature." 

I seen this before especially when site is on https & redirection

This suggest one of CSS or XML file is not using UTF-8 character code.  

However on Chrome, It says 500 error and internal server error. One thing I'm sure the error caused due to any one of like CSS, Image, SVG or XML file is not encoded properly.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have looked in more into and found this error -> 'Fatal error: Allowed memory size of X bytes exhausted (tried to allocate Y bytes)' 

Now, I know I have decreased the memory from 2048M to 64M, partlly due to performance point of view suggested in this link ->https://www.drupal.org/docs/7/managing-site-performance-and-scalability/changing-php-memory-limits.

I have now increased to 128M, so should be enough to work. Annual-summary page has resolved now.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
But not use/1/edit page.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
use edit page has resolved now too. I have increased memory back to its original which is 2048.

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Well I agree that 2048 is huge. I think we had to bump it up for the annual summary (long time ago), but that form now does things very differently. Would it be worth setting it at 1024 as a start?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I just changed it to 1024, see if that is working fine.

**Comment by Gary-van-Breda** [comment]
I suggest we leave this issue open, and if everything is OK over the next few weeks, try dropping it further (512?), and then see how that goes.

I suspect the problem area on the user edit page is the "Where you record" dropdown, as this looks like it holds all locations visible to UKBMS (public, Transect, WCBS BC and BBS), including all the transect subsections, and currently totals just over 129000 (yes, 129 thousand) entries, all in the select dropdown.

@DavidRoy Is this field used anywhere? Can we just get rid of it? We do allow them to separately pick a region.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have decreased to 512 now. I found no problem on user/edit.
Yes, it would be good idea to get rid-off list of 129000 locations from the dropdown list, if possible.

**Comment by DavidRoy** [comment]
@Gary-van-Breda we can remove the 'where you record' element of the account setting

**Comment by DavidRoy** [comment]
Closing now as original issue resolved
