### ISSUE TITLE
Squares to add to UKBMS Online

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#127]
Hi there

Please can these squares be added to the UKBMS online system under the WCBS-BC site type.
[CCC squares.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4134833/CCC.squares.xlsx)

**Comment by Gary-van-Breda** [comment]
@zrandle : do you want the site names prefixed with the "CCC-" ?  
I'll remove the grid reference as that is added automatically in various place, so would end up be duplicated.

**Comment by zrandle** [comment]
Yes please CCC prefix

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by zrandle** [comment]
Great, thank you.

**Comment by zrandle** [comment]
Hi, I've checked this again and we need the grid reference as part of the site name as there are two called Speen. There are two squares at Speen and they have different grid refs so the grid ref is essential to help differentiate. If this could be done asap that would be great - recorders will be starting to set themselves up early next week. Cheers Zoe

**Comment by zrandle** [comment]
Hi 

Please can I have an update on this?

Thanks Z

**Comment by Gary-van-Breda** [comment]
Now fixed: I have added the SREF to the site names as follows: "CCC- Speen (SU8499)" and "CCC- Speen (SU8300)".  
All Sections renamed.  
All sections for SU8300 moved to the correct site - previously they were attached to the SU8499 site: this was because the two sites had the same name, and the data load picked the wrong one.
