### ISSUE TITLE
D8 - User permissions

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#152]
Just tried masquerading as different types of User to see what they can access. Seems very different to the current version.

Normal User:
D7- My Sites, D8 - My Sites AND All Sites - they can also click through to see details of each Site and Route. Is this a deliberate policy? Is it a replacement for the general Site Details pages on the old UKBMS website?
D7 - My Walks, D8 - My Walks AND Branch Walks - not sure they should have an option for Branch Walks when they are not Branch Co-ordinators and won't have any sites assigned to their Branch?
D7 - Timed Counts, D8 My Timed Counts AND All Timed Counts. Do we want everybody to be able to see details of exactly where some priority species are being monitored? There's currently no option to make Timed Counts 'confidential', but they can only currently be seen by Admin.

Branch Co-ordinator:
D7 - My Sites, Branch Sites, D8 - My Sites, Branch Sites, All Sites, Site Assignment - so same query as above for All Sites, but not sure they should have access to Site Assignment unless it can be tailored to only allow them to Assign Sites within their own 'Branch' (not always correlated to a BC Branch). At the moment it looks like they'd be able to Assign Users to any site across the country.
D7 - My Walks & Branch Walks, D8 - My Walks & Branch Walks - same
D7 - Timed Counts, D8 My Timed Counts AND All Timed Counts. As above, I'm not sure they should be able to see all timed counts. But it would be useful in future if we could assign Timed Counts to Branch Co-ordinators and they then had a page for 'Branch Timed Counts'.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you match the functionality to the D7 site as advised above

**Comment by Gary-van-Breda** [comment]
I'll update this comment with ongoing investigations:
1) Normal users & All Sites : Node re-saved, caused permissions to be re-calculated. Now working OK.
2) Normal Users & click through to non-assigned sites: The normal users have always been able to see the data for other sites: if they know the ID they could enter it in the URL, though in normal operation there is no direct access. With (1) above, the D8 should now match the D7. In both D7 and D8, if the normal user is not assigned, then the site is displayed in read-only mode, and the contact details are hidden.
3) Normal Users & Branch walks: Same problem as (1) Node re-saved, caused permissions to be re-calculated. Now working OK.
4) Normal Users & All Timed Walks: Same problem as (1) Node re-saved, caused permissions to be re-calculated. Now working OK.
5) Branch Coordinators & All Sites: fixed by (1).
6) Branch Coordinators & Site Assignment: Same problem as (1) Node re-saved, caused permissions to be re-calculated. Now working OK.
7) Branch Coordinators  & click through to non-assigned sites: See (2) above.
8) Branch Coordinators & All Timed Walks: @IanMiddlebrook : I can't replicate this - which user did you use to see the "All timed counts" for a Branch Coordinators?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
I can't replicate the last one either now, so either I imagined it or it's sorted itself out!

**Comment by DavidRoy** [comment]
Thanks.  Also closing this one, but please add any specific issues
