### ISSUE TITLE
D8 version - data entry form cosmetic improvements

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#158]
Hi @Gary-van-Breda @DavidRoy 

Sorry to keep coming back to the data entry page, but it is the one that volunteers will spend most time on!

The section numbers remaining at the column head as you scroll down the page is good, but it also keeps quite a bit of space above it, leaving less room for species on the screen below. Would it be possible to only have the section numbers remain at the top of the screen, so we can see more species listed as we scroll down?

And also, the two options at the bottom of the page - ie. returning to visit details or finish and return to my walks - they're a little bit hidden. Could these be made to look like buttons with a background colour that will make them more obvious?

Many thanks, Ian

**Comment by DavidRoy** [comment]
Thanks for testing @IanMiddlebrook 
I agree it is worth the effort to polish this page

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've deployed a change to Test so it only displays the section numbers as the "sticky" table header at the top of the screen. I've added a link to the sticky header to jump quickly to the top of the page, so you can change the species grid/list/order easily.  
I've also changed the colours of the link buttons at the bottom, so they look more conspicuous.  
  
Do you want to keep this issue open to track any other issues you find with the form?

**Comment by IanMiddlebrook** [comment]
That's much better, thanks @Gary-van-Breda 

I'll keep the issue open for now just in case, but it's looking good.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : just for your consideration, as part of some ABLE changes, it is now possible to have the species selection autocomplete in the sticky header on the table, above the section headers. It therefore stays on the screen at all times. In addition, when this is switched on, adding a species puts it in into the correct location in the sorted list (as opposed to just adding it to the bottom), and it is scrolled into view. If the species has already been added to the list, rather than just give a warning, the species is scrolled into view.
Would you like me to switch this on, for you to have a go and see if this is preferable to the current way?

**Comment by IanMiddlebrook** [comment]
Sounds good @Gary-van-Breda 
Please switch it on for me to review.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook That's now switched on, on the D8 test site. Please make sure your browser cache is cleared.

**Comment by DavidRoy** [comment]
@IanMiddlebrook please close issue if appropriate
