### ISSUE TITLE
Grid references on WCBS Square Details

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#169]
Hello, new website question: on the site details page for each WCBS_BC and WCBS_BBS square the grid reference appears as a six-figure grid reference. Please can these appear as four-figure (i.e. same as site name) so that the neat coloured 1km square appears on the map view?
Also, please can you make the grid reference un-editable by normal users on all WCBS squares.
Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@DavidRoy : do you want this applied to the Transect site type as well?

**Comment by DavidRoy** [comment]
@IanMiddlebrook do you agree on this for the first part - _please can these appear as four-figure (i.e. same as site name) so that the neat coloured 1km square appears on the map view_

**Comment by IanMiddlebrook** [comment]
Agree with 4-figures for WCBS squares (since the aim is to contain the route within that 1km square). But stick with 6-figures for transects, which provides a central grid ref for the site when the route might be spread over several 1km squares.

**Comment by DavidRoy** [comment]
makes sense to me, thanks for quick reply

**Comment by Gary-van-Breda** [comment]
@DavidRoy : what about part 2?

**Comment by DavidRoy** [comment]
We don't want to change the approach to editing sites.  My understanding is that once they are setup they are 'read-only'.  with @IanMiddlebrook allowing sites to be opened up again for editing.

@IanMiddlebrook can you confirm from transect site perspective

**Comment by IanMiddlebrook** [comment]
Agreed, transect details should be locked once recorders start entering data for that site. They will need to enter a site grid ref when setting up the site details, so that field should initially be available to them.

@MeganLowe can confirm, but I think the problem with WCBS squares is actually recorders changing the Site Name field. For WCBS, the site name should mirror the Grid Ref (eg. XY5678) as set up by the system - with the exception of squares for other projects (eg. CCC, NT prefixes).

**Comment by MeganLowe** [comment]
Hi everyone. Yes I agree with @DavidRoy no change to the approach in editing sites, but at the moment, on the new website, if I masquerade as a normal user I can change both Grid Reference and Site Name on the WCBS squares they are assigned to. On the current website this is not possible. Basically the new website needs to have the same approach as the old - users cannot change the Grid Reference of their WCBS square.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : Code deployed to Test to bring new site into line with previous functionality for all of Grid Reference/Name, attributes and Route Maps: NB normal users _can_ edit the WCBS squares (or Transects for that matter) allocated to them, _but only if they are allocated to them AND there are no walks recorded against the square_.
See also #173, which should also be fixed by this change.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : code deployed and form configured so that WCBS squares have 4 numbers in their SREFs, and Transects have 6.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda Thank you for this. Grid reference/Name looks good now, but I think your change has also prevented normal users from changing all other information on the Site Details form. It would be good if all users were able to select the 'Confidential' tick box in case a landowner changes their mind. @IanMiddlebrook are there any other boxes on this form that you would like normal users to be able to edit? I had wondered about the 'Notes on Land Use and Management'?

**Comment by Gary-van-Breda** [comment]
Can I add the Contact details to this list to be considered?
(This is slightly complicated by the fact that in the old system, they could change all this information on the page, but could not save it!)

**Comment by MeganLowe** [comment]
Ooh yes please Gary - hadn't noticed that on the old site before. Also, sorry Gary(!)... is it possible to add in the 'Links' tab for normal users on the Site Details page please? I think this is a great new feature, but only seems available to Branch Managers and Admin users at the moment?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda , @MeganLowe 
Up to this point we've frozen all details because we don't want recorders changing/moving their route without telling us. But you're right that there are several fields they should still be able to edit without causing us undue concern.
I'd say the only fields which really should be locked to recorders (because they shouldn't change or because we need to be notified if they change) are Site Type, Site Name, Grid ref, No of Sections, Transect Length, Transect Width. The entire Transect Route and the Section Grid Ref Section Length.
We can let them change notes, contact details and habitat/management codes etc, and if we take regular downloads then we'll still have a record of any changes to those fields.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Form change applied to Test, and configured so that once walks are recorded against a site, a normal user can't modify the following fields:

- Site Name
- Site Sref
- Number of sections (Note that the number of sections is fixed for all users for WCBS)
- Transect Width
- The Section Routes themselves.

The Site Type is not modifiable in the Form.
Transect length, Section Sref and section route length are read only to all users as they are calculated automatically.
They should be able to modify all other fields, provided the Site/Square is allocated to them.

@MeganLowe Links Tab is now available to all users who can modify the page (allocated normal users, appropriate branch managers, and site admins): others should not be able to add walks or see the numeric data (annual summary, year and section plots) pointed to by the links, so the tab would be useless for them.

**Comment by IanMiddlebrook** [comment]
Sounds good to me, thanks @Gary-van-Breda

**Comment by MeganLowe** [comment]
Fantastic, thanks very much Gary.
