### ISSUE TITLE
Can you batch mark sites as historic?

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#219]
Hi @Gary-van-Breda and @DavidRoy , more of a question than an issue, but there are a number of historic 'unofficial' WCBS-BC squares on UKBMS with records which currently show up on the Sites Map. These are causing a few issues as recorders are getting in touch wanting to survey them. I'd like to get around this by marking them 'Confidential' so they don't appear on the map, but I wondered if you have a way to do this in a batch if I sent you a list of the sites, rather than me having to open up each individual site and save it as confidential? There are over 100 of them. Thanks, Megan.

**Comment by Gary-van-Breda** [comment]
Yes: technically we can either run a database statement to set the flag on the location, or create a small form which will do it for us.
  
Would you want both the Locations and the Occurrences marked as 'Confidential'?
  
It would be better to actually add a "Historic" attribute (checkbox) to the locations, that we would filter the sites report on. I'd be averse to using the same flag for multiple purposes, especially one with a specific name: it will get confusing in the future, and really adding a new flag doesn't add that much of an overhead.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda apologies for the delay (my other role has been taking much of my brain power recently). Yes I agree a historic attribute sounds much more suitable - that would be great, yes please. Thank you, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : Is this historic flag only for WCBS-BC sites, or should it also be on Transect and WCBS-BBS sites?
Can you also give me the URL(s) of the page(s) which you would like historic sites excluded from?
Thanks

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda yes only for WCBS-BC please. This is the page I would like historic sites excluded from: https://ukbms.org/sites
Is it possible to make these historic checkboxes only viewable/editable by Admin Users? Thanks, Megan.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : code deployed to Test site for review.
The historic site attribute is a checkbox that is hidden on the site data entry page unless you are an admin (see caveat below)
It is available on the "All Sites" as an updateable checkbox, similar in concept to the Code field, so the sites can all be set to historic on that page. The "All Sites" page is only viewable by Admins.
The sites page report has been updated so that it does not display historic sites.

Because the historic attribute has had to be added to the live warehouse in order to test this, when it is finally deployed to Live you should check any sites already set to historic at that point, as normal users will have been able to set the historic flag on the Site Data Entry form until these changes are deployed.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda that's great, looking and working well for me so happy for it to be deployed to live. Thank you!

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Site DE entry page configured to hide the Historic flag from non admins,
All sites page reconfigured to allow update of the historic flag for WCBS-BC only.
No reconfig required for sites page as just the report internals have changed.

Only location with historic set is ST5537, last edited by @MeganLowe - I assume as part of testing of this above.

Closing.
