### ISSUE TITLE
Walks hiding from view

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#236]
Hi @Gary-van-Breda @DavidRoy 

We have a situation where a walk (sample) has been entered by a recorder, everything appears superficially OK. The butterfly counts can be seen in the Annual Summary table etc, and are available in the various downloads.

However, if anyone (recorder, co-ordinator, admin) tries to edit or review the Walk Data Entry form for that walk, it doesn't seem to exist. They are just faced with a page of blank fields apart from their own name in the recorder field (as if they were starting a new walk).

On further examination, it seems that the second data entry page (i.e. butterfly counts) has saved, but the first data entry page has not. The first tell-tale is in the Raw Data table, where no Temperature is displayed, even though there is a figure for average Sun%. Looking at the Samples Download, it seems all that is saved are the site details, visit date and Notes field.

I have found 4 samples that  this applies to, though there may now be more:
14408533, 14089401, 14054340, 14080651

Can the missing fields be rescued, or will we need to delete those samples and re-enter?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook All these do still exist and were originally saved correctly complete with the missing data, but at a later point the attributes have been corrupted - the attribute records have been effectively hijacked, and used for a different walk. This may have been for example due to a data fix for a different issue - I'm not sure.
The easiest thing to do would be to edit the records and manually re-enter the missing data. [it may be possible to recover the data from the audit tables, but there is no guarentee and it would take quite a bit of effort]
