### ISSUE TITLE
Data Entry page not populating in Internet Explorer (or Safari ?)

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#249]
Hi @Gary-van-Breda 

We've had a few reports of recorders being unable to enter data because the data entry screen does not populate with any specie list. As far as we can tell, this issue is restricted to recorders using Internet Explorer.
We have suggested they use a different browser, but wanted to raise it as an issue in the hope it can be addressed, or in case it points to a wider issue.

Thank, Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda ,

We have had additional feedback from a Mac user who cannot bring up a species list during data entry when using Safari:
![Safari Data Entry Screen](https://user-images.githubusercontent.com/24699793/138427513-4717eb96-3c29-46ff-a319-c68f6a3b565e.jpg)

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@DavidRoy : since the antibot module was deployed (within the last couple of months), I can't log in to ukbms.org using Internet Explorer. I get a 'You have reached this page because you submitted a form that required JavaScript to be enabled on your browser' error.

- Does anyone else have this problem?
- Do we still support IE as a browser? 

Unfortunately I do not have a Mac, and Windows Safari is so far out of date as to be useless for debugging this. Is there anyone I can contact so I can debug this issue?
