### ISSUE TITLE
Test UKBMS Drupal 7 site: time count entry page issues

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#25]
Some issues on http://192.171.199.230/ukbms/mydata/input-timed-counts?date=03/05/2016

1. The warning text should not be in red font (e.g. The Year field is read-only, and is calculated automatically from the date(s) of the Counts.).  Should this message appear by default in any case?
2. Map does not zoom to selected county
3. 'Search for place' does not work
4. Map selection does not populate grid reference field

**Comment by Gary-van-Breda** [comment]
pt2: Currently the County is just an attribute against a termlist, it is not looking up the Indicia Locations list, which would be required in order to get the size/location of the county to zoom to it. Do you want this changed?

pt3: I've swapped the search from Yahoo (now defunct) to Google. @BirenRathod : can you check the GoogleMap API key being used is valid for http://test.brc.ac.uk/ukbms/mydata ?

pt4: I've had no problems - when the polygon is drawn, the grid ref is filled in. Can you give more details in order to reproduce?

**Comment by BirenRathod** [comment]
@Gary-van-Breda , I just added the Google API key, so should be fine. Although I tried to search place which has returned with no result. Is this expected to be like that?

**Comment by Gary-van-Breda** [comment]
No: the response from Google is 

"This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_"

Also the maps are throwing out the following:

"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

**Comment by Gary-van-Breda** [comment]
PT1: New code has been deployed: Year warning/info text is now help text under the year field, and the instructions to draw the flight area are no longer red.

**Comment by BirenRathod** [comment]
Sorry @Gary-van-Breda, it is my mistake. I stored the wrong API key. I have now upgraded with right one.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : pts 1,3,4 sorted. See above for comment on pt2.
