### ISSUE TITLE
Sites map has no Sites on it

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#264]
Hi @DavidRoy @Gary-van-Breda 

A colleague has just pointed out to me that the map of site locations is not displaying any Sites at the moment:
https://ukbms.org/sites 

Thanks, Ian

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please
including @burkmarr who developed this page I believe

**Comment by BirenRathod** [comment]
@burkmarr the report branch_sites didn't find location_attribute_id = 322. Any idea?

**Comment by Gary-van-Breda** [comment]
The initial "disappearance" issue is due to a change for issue #219: I wasn't expecting the report change to be promoted to warehouse1 just yet. I've lodged a fix to the projects/ukbms/ukbms_sites.xml report: @BirenRathod can you copy the new report version over to warehouse1? Thanks
Is there an issue with branch_sites report?

**Comment by BirenRathod** [comment]
@Gary-van-Breda I pulled that report now. Due to that the query in that report takes so long to process and ukbms.org/site page show "The application did not respond in time.". 

Not sure what have you changed in it but ukbms_sites report was working fine before and problem of using branch_sites report too.

**Comment by Gary-van-Breda** [comment]
Sorry - just spotted a bug in the new join in the ukbms_sites report. Code fixed and lodged. @BirenRathod can you copy the new report version over to warehouse1 again? Thanks.

What is wrong with the branch_sites report?

**Comment by BirenRathod** [comment]
@Gary-van-Breda I have pulled that report now and nothing wrong with branch_sites report.
@IanMiddlebrook this has resolved this problem. please close it.

**Comment by IanMiddlebrook** [comment]
Thanks all
