### ISSUE TITLE
WCBS square section grid refs

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#269]
Hi @DavidRoy ,

A county recorder has pointed out that some WCBS square data are coming through with odd grid references.

These are specifically linked to squares where we have not yet digitised the true route, and they still have 10 small squares arranged from bottom left up to top right, within the 1km square. 
The section data are supplied with the grid refs for these 100m squares, which are unlikely to be accurate. It would be better if section data were just supplied with the 1km grid ref until such time as a true route has been drawn for that square.

Is this possible?

Thanks, Ian

**Comment by DavidRoy** [comment]
@Gary-van-Breda - can you advise on this?  Is the best option to give all the sections the parent 1km grid reference priory to the route being digitised?

**Comment by Gary-van-Breda** [comment]
@DavidRoy Yes - probably best option is to set the geometry of the sections to be the same as the site, if the section path has not been filled in (ie it is a square rather than a line).

Do we need to alter the samples that have been previously been recorded against the small square sections? (which would mean updating the cached occurrences, and the elastic search data as well).

**Comment by Gary-van-Breda** [comment]
Data fix applied to change all the section sref/geometries to match the square's/site's for WCBS sections where the path has not been filled in (i.e. not Linestrings): also updated the samples on these sections to match those new sref/geometries.

The cached values should be updated by the scheduled tasks.

No need to run the summary_builder (as the annual summary has not interest in the geometries).

**Comment by IanMiddlebrook** [comment]
Thanks
