### ISSUE TITLE
Data entry Warnings - additional issues

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#272]
<img width="653" alt="warning" src="https://user-images.githubusercontent.com/88440885/164224274-5c368c2f-8217-43fa-8f5c-203606d40a0c.png">

"The value entered for this taxon on this transect section (5) exceeds the expected maximum (undefined)"

Users reporting a pop up when submitting other taxa. I was able to recreate and also received it when submitting a Cryptic Wood White ( I am in Northern Ireland and should be able to submit CWW) but I didn't get it for Large Skipper, Brown Hairstreak. The transect has an NI Grid ref.  I think this error pop up is for distribution but the wrong way round (as for English Transect). As with other issue, there are no warnings generated for flight period.

**Comment by JimBacon** [comment]
@Gary-van-Breda Will you fix this at the same time as #271? The word `undefined` needs to be in quotation marks at line 2442 of `ukbms_sectioned_transects_input_sample_2.js` in the `checkSectionLimit` function.

**Comment by JimBacon** [comment]
@IanMiddlebrook Each species has an attribute setting the maximum number that you might see on a section before raising the above warning. The following taxa do not have the value set. Is this something you would like to alter? It makes no allowance for your location and is independent of the verification rules for flight period and distribution.

_Nymphalis polychloros_, Large Tortoiseshell
_Leptidea juvernica_, Cryptic Wood White
_Danaus plexippus_, Monarch
_Lycaena dispar_, Large Copper
_Nymphalis antiopa_, Camberwell Beauty
_Colias hyale_, Pale Clouded Yellow
_Colias alfacariensis_, Berger's Clouded Yellow

**Comment by RachaelConway** [comment]
Hi all, the warning appears when the max number is 1,  the CWW should probably be removed from this list,  it is commonly recorded on transects in Northern Ireland

Users also getting warning when submitting other species eg. moths; warning on submission in 1 x Silver Y
<img width="630" alt="max 1" src="https://user-images.githubusercontent.com/88440885/164427466-cf4b0070-cbd5-487c-a477-a69ef789578a.png">

**Comment by IanMiddlebrook** [comment]
Hi @JimBacon 

Cryptic Wood White should have a maximum of 20, to bring it in line with Wood White.

The others are all rare migrants - they certainly need some sort of warning on them, and I've a feeling they don't all have verification rules for flight period or distribution (due to lack of data). Perhaps set a maximum of 1 (or zero) for these species, but really they need a different message - "This is a rare migrant species - only record if you are certain of the identification".

Thanks, Ian

**Comment by JimBacon** [comment]
Hi @RachaelConway, Thanks for the feedback. It is really useful.
 
There are two problems interacting with CWW. One is that there is no maximum number set in the configuration and the other is that there is a bug in the code which causes this message to pop up because of the missing configuration. I've done as Ian suggested and have set a limit of 20 for CWW and now you get no message for 20 or below but the warning appears for 21 or more. The bug is not yet fixed, it simply does not manifest itself now that I have configured a maximum value.

**Comment by JimBacon** [comment]
For moths, odonata, and others we do not configure a maximum value and so the bug manifests itself in all cases.

**Comment by JimBacon** [comment]
@IanMiddlebrook I've created issue #273 for your suggestion of warning on recording rare migrants. @DavidRoy can prioritise and allocate.

**Comment by DavidRoy** [comment]
Thanks @JimBacon.  Best for @Gary-van-Breda to pick this up when fixing the wider bug.  By definition, rare migrants will not often be entered

**Comment by Gary-van-Breda** [comment]
Thanks for the pointer @JimBacon 
@RachaelConway Code fixed and deployed to Live

**Comment by RachaelConway** [comment]
@Gary that all seems to be working Ok, Thanks
