### ISSUE TITLE
Data Entry WCBS-BBS

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#274]
Hi, a recorder has reported that when they try to submit their WCBS-BBS records the data entry form displays duplicate sections (see image below). I can't work out what is going on to cause this - please can someone take a look? Thanks, Megan
![image](https://user-images.githubusercontent.com/64081219/165252238-477ece2f-28c4-4b3b-ae87-b3ffba4e80d1.png)

**Comment by MeganLowe** [comment]
Hello, just to let you know we are still having issues with data entry for this square - I've tried entering data for a few different WCBS-BBS sites and can't replicate the problem so I think the issue may lie with just this square.

**Comment by MeganLowe** [comment]
Please can someone take a look at this issue - the recorder has three visits worth of data to submit now and we're not sure what to do.

**Comment by Gary-van-Breda** [comment]
@Megan, it does look like this is a restricted issue. I have removed the duplicated sections (they had no taxa associated with them), and it now looks OK.

**Comment by MeganLowe** [comment]
Thanks @Gary-van-Breda looks good.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda , I'm afraid I've been sent news of another one: WCBS-BBS square SD4083 has the same issue with the multiple columns for each section on the data entry form. Please can you fix this one? Is there a way for you to check the other BBS squares too for this issue? I'm worried that we'll start finding more once the main survey season begins next month! I wonder if it has anything to do with the routes that were uploaded on mass earlier in the year?!

**Comment by DavidRoy** [comment]
@JimBacon can you look into this when you get a chance.  It may relate to loading of WCBS-BBS geometry for the transect routes?

**Comment by JimBacon** [comment]
Location ID 98461 is the location of type WCBS-BBS with name SD4083.
It has 10 sections and every one is duplicated, see https://warehouse1.indicia.org.uk/index.php/location/edit/98461

There are samples submitted against both sets of sections and the two sets have slightly different geometries. The original set was created in June 2015. The more recent one was created by Richard Burkmar on 11th March this year.

A rough check to look for other transects with similar problems suggests there are a couple of hundred.
```
with dups as (
	select parent_id, code, count(*)
	from locations l 
	join locations_websites lw
		on lw.location_id = l.id and lw.deleted = false
	where lw.website_id = 27
		and l.deleted = false
	group by parent_id, code
	having count(*) > 1
	order by parent_id, code
)
select count(distinct parent_id)
from dups
```

We would need to know which set of sections to keep, move all the existing samples to them, then delete the sections we don't want. @burkmarr do you have any extra info which would be helpful in regard to this?

**Comment by MeganLowe** [comment]
Hi @JimBacon , we updated the route maps for BBS squares earlier in the year so I'm going to guess that the ones with two different sets of geometries are where the route has been tweaked between years or where a recorder originally 'drew' the route inaccurately. The set we would want to keep would be the most recent, but obviously we don't want to lose any of the previous samples... Thank you for your help!

**Comment by burkmarr** [comment]
Hi @JimBacon. Looking back over what I did for @MeganLowe in March, I found this issue: https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/255. It looks like I did a complete update of all WCBS-BBS child transect sections using the Warehouse location geometry update feature with data derived from a shapefile supplied by the BTO. I think that I updated the WCBS-BBS transect sections for each transect by matching on their names which I thought were all of the format `<monad> S<section>`. The sample of the problem transect sections you identified above appear to have originally had the name format `<monad> - S<section>` so instead of updating the existing geometry for these transect sections, it looks like the update has added them for the parent section. That could be the root of the problem. I'm in the office tomorrow (Tues and Weds) and we can have a chat about it.

**Comment by burkmarr** [comment]
@JimBacon - in answer to your direct question, the sections to keep would be the newer ones without the hyphen since they have the latest geometry from the BTO.

**Comment by MeganLowe** [comment]
Hi @JimBacon and @burkmarr, thank you for looking at this. Is it possible to fix this ASAP? The species data submitted to these squares are not appearing to save properly (abundance counts are all blank). If not possible to fix within hours, please could you send me a list of all affected squares so that I can contact the recorders and ask them to retain offline copies of their records until we have applied a fix? Thank you!

**Comment by burkmarr** [comment]
@MeganLowe - it looks like Jim is away at the moment. I will look at it now and let you know where I get with it this afternoon.

**Comment by burkmarr** [comment]
@johnvanbreda - can you give a quick check over on what I'm planning to do to resolve this?

Jim's suggested workflow:

> We would need to know which set of sections to keep, move all the existing samples to them, then delete the sections we don't want

I have  query to create a temp table that matches the old sections to the new ones (see below). The temp table looks like this:

![image](https://user-images.githubusercontent.com/9275178/184151488-7c924275-58f0-4661-99eb-a7ed3a4f3469.png)

Can you check the steps below to see if they are right and if anything is missing?

- Update samples table - update any undeleted samples with `location_id` matching `old_section_id` so that `location_id` is set to `new_section_id` (also update `updated_on` and `updated_by_id` fields). 
- Update locations table - set deleted flag to true where `id` matches `old_section_id` (also update `updated_on` and `updated_by_id` fields).

(The SQL for creating the temp table is below.)

```
with dups as (
	select lp.name as parent_name, l.parent_id, l.code as section_code, count(*)
	from locations l 
	join locations lp on lp.id = l.parent_id
	where lp.location_type_id = 5195 -- 5195 is WCBS-BBS
		and l.deleted = false
		and lp.deleted = false
	group by parent_name, l.parent_id, section_code
	having count(*) = 2
	order by parent_name, section_code
)

select lold.id as old_section_id, lold.name as old_section_name, lnew.id as new_section_id, lnew.name as new_section_name
	into iss_ukbms_274
	from dups d
join locations lold on lold.parent_id = d.parent_id 
	and lold.code = d.section_code
	and lold.deleted = false
	and lold.name like '% - %'
join locations lnew on lnew.parent_id = d.parent_id 
	and lnew.code = d.section_code
	and lnew.deleted = false
	and lnew.name not like '% - %'
```

**Comment by burkmarr** [comment]
@MeganLowe - I will return to this tomorrow morning. For now I will email you the list of affected transect squares as requested.

**Comment by johnvanbreda** [comment]
@burkmarr I think I'd want to scan the output of your temp table to check that the min and max of new_section_id confirm they are all from the range of locations you imported in #255 - any outliers might need investigation but hopefully there aren't any.

Also, if you are updating the location IDs in the sample, we need to consider whether the sample geometry should also be updated to that of the new locations? If the new locations genuinely reflect the route taken then that would be a good idea (though not as high priority as sorting out the duplicates).

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I'll double-check the new_section_ids.

> If the new locations genuinely reflect the route taken

@MeganLowe - is it fair to say that the new geometries you sent were a more acurate representation of the original transect sections rather than a change to them?

**Comment by MeganLowe** [comment]
Hi @burkmarr, I suspect the majority would have been more accurate copies of the same original route, but it's likely there were some that included changes to previous route (due to access issues/barriers etc). The shapefiles were sent to me from the BTO, hence the slight uncertainty.

**Comment by burkmarr** [comment]
@MeganLowe - okay let's stick with the immediate problem of removing the duplicate transects and reasigning samples to the new transects for now. The sample geometry can be updated later where required.

**Comment by burkmarr** [comment]
@johnvanbreda - below is what I've done. Do I need to update the sample cache tables?

Check that sections indicated by new_section_id in iss_ukbms_274 were all created by me when I did the update:
```
select l.created_by_id, date(l.created_on), count(*)
from iss_ukbms_274 i
join locations l on l.id = i.new_section_id
group by l.created_by_id, date(l.created_on)
```
Result: 198219 2022-03-11 1908

Assign samples from old locations to new:
```
update samples 
set location_id = u.new_section_id, updated_on = NOW(), updated_by_id=198219
from iss_ukbms_274 as u
where samples.location_id = u.old_section_id
and samples.deleted = false
```
Result: 7582 rows updated

Update the locations:
```
update locations
set deleted = true, updated_on = NOW(), updated_by_id=198219
from iss_ukbms_274
where locations.id = iss_ukbms_274.old_section_id
and locations.deleted = false
```
Result: 1908 rows updated

**Comment by johnvanbreda** [comment]
@burkmarr you can either put a cache update in the work queue for the samples cache tables, or you can just update location_id and location_name for the cache_samples_functional records that correlate to the ones you changed.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I did the latter.

```
select s.id as sample_id, s.location_id as location_id, l.name as location_name into iss_ukbms_274_updated_samples from samples s
join locations l on l.id = s.location_id
where Date(s.updated_on) = Date(Now())
and s.updated_by_id = 198219

update cache_samples_functional
set location_id = u.location_id, location_name = u.location_name
from iss_ukbms_274_updated_samples as u
where cache_samples_functional.id = u.sample_id
```

**Comment by burkmarr** [comment]
@MeganLowe - Hopefully that will have sorted it. Can you check that things look better from the website?

**Comment by MeganLowe** [comment]
Hi @burkmarr, thank you that looks a lot better! The duplicate sections have gone, but we're still missing abundance counts for records that were submitted via the dodgy forms - do you think that is because they literally didn't save, or could they be hidden behind the scenes somewhere?

**Comment by burkmarr** [comment]
That's good news @MeganLowe. Can you give me any details for some of the records that you can't find to help me track them down? For example dates, transect square, species etc?

**Comment by MeganLowe** [comment]
@burkmarr one example would be SY4694. The recorder has submitted samples on 18th July and 8th August. I can see which species they recorded in each section (for example Meadow Brown was the only butterfly reported in S4 on 18th July) by downloading all BBS data, but the abundance count column is blank. Thanks again for your help!

**Comment by burkmarr** [comment]
>  you can just update location_id and location_name for the cache_samples_functional records that correlate to the ones you changed.

@johnvanbreda - do I need to do the same for the cache_occurrences_functional table?

**Comment by johnvanbreda** [comment]
@burkmarr yes, good point.

**Comment by burkmarr** [comment]
Updated cache_occurrences_functional:
```
update cache_occurrences_functional
set location_id = u.location_id, location_name = u.location_name
from iss_ukbms_274_updated_samples as u
where cache_occurrences_functional.sample_id = u.sample_id
```

**Comment by burkmarr** [comment]
@MeganLowe - can you see what difference that has made?

**Comment by MeganLowe** [comment]
Hi @burkmarr sadly not much in terms of the abundance counts (they are still blank) - is it therefore safe to think that the records didn't save and I should ask recorders to re-submit? Thanks

**Comment by burkmarr** [comment]
@MeganLowe - the details you gave me to follow up don't appear to match what's in the DB. Here are all the 2022 records for the WCBS-BBS square SY4694:

![image](https://user-images.githubusercontent.com/9275178/184637096-adaa116d-e700-4f5e-8cd7-5489f4e51f31.png)

So there are a couple of records on the dates you mentioned with null counts, but not for Meadow Brown. And there is a record *with* a count for Comma entered on 12th August - but I guess this could have been entered after the problem was sorted. It *is* looking like the numbers will need to be re-entered. Are your recorders able to update any problem records and re-enter the counts?

**Comment by burkmarr** [comment]
@MeganLowe - I will send an email to ask you for a username I can use to see this for myself.

**Comment by burkmarr** [comment]
Hi @MeganLowe . I found out why I was only retreiving those three records - it was indeed because there is no abundance_count attribute at all in the database for the other records. When I retrieved all the records regardless of whether or not there is an abundance_count attribute, I see records for all the species on those two dates that I can also see in the section plot summary on the UKBMS site. 

So in summary there are two records (indicated above) for those the two dates you mentioned *with* and abundance_count attribute, but the value is set to null and the remaining records for those dates have no abundance_count attribute at all. So it does look like the abundance data has not made it into the DB and will need to be re-done.

You know UKBMS site better than I do - is it possible for the current records to be updated or will they need to be re-entered from scratch? If they need to be re-entered, then we need to find a way to delete all the current records that have no abundance counts.

**Comment by burkmarr** [comment]
@MeganLowe - I've identified 435 records from 2022 that have either no abundance_count attribute at all or the value set to null. I can send you a spreadsheet that identifies the transect, transect section, record date and species if that helps you.

**Comment by MeganLowe** [comment]
Hi @burkmarr thank you for looking in to this. Ashame that the abundance counts weren't hiding somewhere, but it was worth checking! I will ask the recorders to submit their counts again - they will be able to update the current records, but some may choose to enter again from scratch as that's easier for them. I've already made a note of all of the affected samples so will keep checking and remove the records with no abundance count as and when needed. It may be useful to have sight of your spreadsheet too just to make sure I haven't missed any. Thanks again!

**Comment by burkmarr** [comment]
OK @MeganLowe - that's great. I'll email you the list I have.

**Comment by DavidRoy** [comment]
@MeganLowe closing now but please re-open or add new issue if needed
