### ISSUE TITLE
Function to allow removal of species from 'other' list

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#278]
Hi All, 

A transect walker has added Wood White into the 'other' list. This is preventing him from adding Wood White into his species list. Please see image of error message. Please can you advise if there is anyway species can be removed or we can get Wood White into the species list. Thanks 

![image](https://user-images.githubusercontent.com/88440885/174654009-aef2c307-10f8-41ab-906d-0b527d87ec4d.png)
![image](https://user-images.githubusercontent.com/88440885/174654226-1f8aea69-a3b4-4b58-940e-1ec555582b5b.png)

**Comment by RachaelConway** [comment]
Hi @DavidRoy and @Gary-van-Breda , this issue still remains for this user. he would like to have Wood White in his species list. Please can we remove the Wood white from his 'other' list so he may record it with his site species
<img width="278" alt="image" src="https://user-images.githubusercontent.com/88440885/232803559-1f038d58-12a4-4d11-b185-4a0c35be4dad.png">

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @Gary-van-Breda etc, 

A little more info on this bug - it's only when he's entering a new walk that Wood White appears in the 'Others' list, but not in the Butterflies list.

When he reviews previous data, Wood White appears back in the Butterflies list rather than 'Others'.

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 
We are in danger of losing a volunteer over this issue, which has been untouched for nearly a year:

_I now have Wood Whites to record, but they still do not appear in the butterfly list, so there seems little point in me entering my data, or indeed in carrying on the transect, if I cannot record the most important species there in the right place!
Please can we get this fixed—it surely can’t be too difficult?_

Could we please get somebody to look at it?

Thanks, Ian

**Comment by JimBacon** [comment]
Investigation notes:

- On page load, 
   - all the species flagged as common in the UKBMS Butterflies list are retrieved. (ukbms_sectioned_transects_input_sample_2::commonSpeciesList())
   - all the species that have been recorded at the transect are retrieved from the `summary_occurrence` table. (ukbms_sectioned_transects_input_sample_2::allSpeciesAtTransect())
- These lists are used to pre-populate the species grids on each tab.
   - Butterflies shows the 19 common butterflies in the UKBMS list (id = 51).
   - Moths shows the subset of species that have been recorded at the transect in taxon_list = 15 (UK Master list) and taxon_group = 'insect - moth'
   - Dragonflies shows the subset of species that have been recorded at the transect in taxon_list = 15 (UK Master list) and taxon_group = 'insect - dragonfly (Odonata)'
   - Others shows the subset of species that have been recorded at the transect in taxon_list = 15 (UK Master list) of any taxon group not already in another grid.
- Wood White is in the list of species that have been recorded at the transect but it is not a common species. It is the only butterfly species which has the same taxon_meaning_id in the UK Master List and the UKBMS List which is why a problem is encountered. It matches the criteria to appear on the Others tab which then prevents it being added to the Butterflies tab.

**Comment by JimBacon** [comment]
There have been problems around Wood White before.
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/32 details problems which arose when the taxon_meaning_id changed to its current value.
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/242 is similar to this issue but blames the problem on an original record being made on the Other tab against the UK Master List.

The `summary_occurrences` table shows records have been recorded against the following taxa for the UKBMS Transects survey

taxa_taxon_list_id |taxon list | taxon | number
---|---|---|---
283038 | UKBMS Butterflies | Leptidea sinapis | 1608
283039 | UKBMS Butterflies | Wood White | 48
151131 | UK Master List | Leptidea sinapis | 11

Querying `cache_occurrences_functional` returns 25 records for the UKBMS Survey recorded against _Leptidea sinapis_ in the UK Master List. These were made at Grafton Wood and Sywell Wood. That may be a problem which needs addressing but is not the problem we have in this issue which relates to Leckhampstead Wood (location_id = 275951).

**Comment by JimBacon** [comment]
The problem should resolve if the record for Wood White in the UKBMS Butterflies list has a `taxon_meaning_id` different from in the UK Master List. To set the `taxon_meaning_id` back to its original value, the following queries were performed.
```sql
-- Insert the original taxon_meaning_id in to the taxon_meanings table.
insert into taxon_meanings
values (127651);

-- Update taxa_taxon_lists with the new taxon_meaning_id
update taxa_taxon_lists
set taxon_meaning_id = 127651, updated_on = now(), updated_by_id = 2
where taxon_meaning_id = 393298
	and taxon_list_id = 51

-- The cache_taxa_taxon_lists, cache_taxon_searchterms and cache_taxon_paths 
-- tables will be automatically updated by the scheduled tasks.

-- Update cache_occurrences_functional with the new taxon_meaning_id (12065 updates)
update cache_occurrences_functional
set taxon_meaning_id = 127651
where taxon_meaning_id = 393298
	and taxa_taxon_list_id in (283038, 283039)

-- ElasticSearch indexes will be automatically updated by the scheduled tasks.

-- Update summary_occurrences with the new taxon_meaning_id (1736 updates)
update summary_occurrences
set taxon_meaning_id = 127651
where taxon_meaning_id = 393298
	and taxon_list_id = 51
```
There was a little additional wrangling because there are two deleted taxa records for Wood White in the UK Butterflies list, the presence of which prevented the scheduled tasks updating `cache_taxon_search_terms` while undeleted and deleted records had the same taxon_meaning_id.

My test shows this has resolved the reported issue.

**Comment by JimBacon** [comment]
@IanMiddlebrook could you contact the recorder to see if I have solved their problem. Close the issue if everything is okay.

**Comment by IanMiddlebrook** [comment]
Hi @JimBacon  
The recorder has now tested this, and their problem is solved.
Many thanks, Ian
