### ISSUE TITLE
Unable to approve new user

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#285]
Hi @DavidRoy ,
I think this issue has come up before, but we're unable to 'unblock' a new user (Steve Orridge) due to the following issue:

![image](https://user-images.githubusercontent.com/24699793/192722245-83aaaf52-be2a-4e8a-96ae-8bbb91f3bc81.png)

There are no websites listed, and even if there was, it would be difficult for us to answer that on behalf of the user.

What is the best way to resolve this?

Thanks,

Ian

**Comment by DavidRoy** [comment]
@JimBacon could you pick this one up please

**Comment by JimBacon** [comment]
Hi @IanMiddlebrook 

I have made two changes to the code. 

1. I fixed the bug which prevented the list of websites from being displayed.
2. I changed the logic so that the list of websites is only displayed to the user as it is not feasible for you to answer the question on their behalf. As and admin, you are shown a warning about the problem like "There appear to be several existing users on the central records database for Jim. They need to log in to this website to resolve the issue." 

When the user logs in to the website then they will be presented with the question of resolving their multiple users.

One thing I'm not clear about is whether a user might be using a mobile app and never visiting the website. If that is possible then I think you would need to email the user asking them to log in to the website otherwise things won't work as they should. This should be a rare occurrence as the multiple users is a relic of an old bug.

Please could you test this out by unblocking the user you were having difficulty with. Thanks.

**Comment by IanMiddlebrook** [comment]
Thanks @JimBacon 

Yes, I've been able to unblock him.
There's no mobile app for the UKBMS website.
