### ISSUE TITLE
abundance figures missing from some section data

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#316]
Hi @DavidRoy @Gary-van-Breda 

A recorder has noted that some of his data are disappearing.

The site affected is Packwood House (location_id = 192766), and all data this year for sections 3-7 have been saved with the abundance field blank (blank in the relevant downloads, and also blank if you go back to check the data entry page).

Coincidentally, these sections are doubled up on the data entry page for this transect - a long-term issue also affecting a few other transects, but not affecting data up to this point.

Checking through more data, I can see that this loss of abundance data is affecting a few other sites, including - 
Kelsall 1 (id = 207205) - sections 2 and 3
WWT Llanelli Millennium Wetlands (id = 165512) - section 2

Could we please find out what is happening to the abundance counts, and now that is having an impact on the data, resolve the long standing issue of sections doubling up on the data entry page? issue #75 

Many thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 

Any movement on this one? We have a very frustrated recorder.

Best wishes, Ian

**Comment by DavidRoy** [comment]
@JimBacon could you look into this

**Comment by RachaelConway** [comment]
Hi @JimBacon 
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/30502f85-8877-48ce-bb7e-7aadb634488c)
The Llanelli surveyor has reported that there is a doubling up of section 2.

**Comment by JimBacon** [comment]
Sorry for the delay. Been on leave. Looking now.

**Comment by JimBacon** [comment]
I will remedy #75 and expect the missing data to then become visible.

**Comment by JimBacon** [comment]
Unfortunately it seems that the abundance data for species recorded in the duplicate sections has not been saved on most records made from 2021. Up to and including 2020 there is no problem. Presumably there was a code update at that time which caused this change of behaviour. Since it is incorrect that there should be duplicate sections, it is not surprising if the code did not handle the situation well.

Having eliminated the duplicate sections from the above transects, recording now works correctly.

Regrettably, the only way to correct the missing data is to edit the records and enter the missing abundance data. I apologise for this inconvenience and the error which caused it.

To avoid a repetition of this, the lesson is not to submit records against a transect until it is correctly defined.

**Comment by IanMiddlebrook** [comment]
Thanks @JimBacon 

@RachaelConway - I've let the recorders at Packwood know. Could you inform anyone else who was affected by this?
