### ISSUE TITLE
Duplicated location_ID means unable to edit data entries for a site

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#324]
Hi @DavidRoy @JimBacon 

We have a situation where an apparent duplication of a site/location_ID has made it impossible to edit entries for that site.

The site - Stoke Park, Bristol (location_ID 301909) - appears twice in the Site Assignment list for Somerset & Bristol branch:
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/62dbdfd3-df86-459a-ace0-ed31694938f0)
Although it only appears once in Site Lists for individual recorders, or on the Annual Summary page, so the Site Assignment page is the only indication that there might be a problem.

However, if you try to edit and of the walk entries for this site, you get this message:
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/8cbf5136-f6fc-4f67-a64a-c1df2881233f)
Some sample links for example:
https://ukbms.org/input-data?sample_id=23774467
https://ukbms.org/input-data?sample_id=23226073

Please could we resolve this issue so that entries can be edited?

Many thanks, Ian

**Comment by JimBacon** [comment]
I don't have an explanation as to how this has arisen but the problem is caused by there being duplicate records in the locations_websites table. There was one other transect with the same problem, Bladnoch, with location_id = 320054. I have deleted the duplicates for both locations which relieves the issue.

Note, the created_on and created_by_id fields indicate that the problem was introduced at the time of creation of the locations. Each duplicate pair was created by the same user (but a different user for the two transects), separated by a few minutes.

**Comment by IanMiddlebrook** [comment]
That's great - thanks @JimBacon
