### ISSUE TITLE
? Rule check/ warning flag disabled on UKBMS submission form ?

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#349]
@IanMiddlebrook @DavidRoy 

Hi is the rule check function on the UKBMS submission form disabled?

Following CR query re some suspect records:

Distribution - I've been able to submit Mountain Ringlet and Cryptic Wood White to a Somerset transect.
Phenology - Purple Hairstreak also not flagged 
Rare Migrant is triggering flag

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy  @Gary-van-Breda 

I know the data entry rules (out of range/time of year) were disabled at some point last summer due to slowing down the website, but they were then re-instated after some improvements - I think this was the issue - #305 
I'm not aware of any subsequent reason for the rules to be switched back off?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
The walk limit/rare migrant checks were enabled - this outputs a warning dialog requesting confirmation Yes/No.

The Geographic/Date range checks were switched off - I have just re-enabled them. These just highlight a row with a warning triangle & pale red colour, with no dialog and will not prevent entry of data in any way.

FYI @IanMiddlebrook @DavidRoy

**Comment by RachaelConway** [comment]
Grand job thanks
