### ISSUE TITLE
Confidential Sites have disappeared from Annual Summary Page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#365]
Hi @DavidRoy @Gary-van-Breda 

The Annual Summary page no longer lists any of the Sites that have been marked as 'Confidential', which means I'm unable to access their 2024 counts.

For an Admin User, these Sites used to be listed there in italics (in the drop-down list 'filter by site'). 
I've checked that these Sites are visible to Branch Managers, and that's OK, it's just Admin that should see them but can't.

This is critical for data validation.
It is possibly a repeat of issue #345 which occurred back in January?

Many thanks, Ian

**Comment by andrewvanbreda** [comment]
I will take a look at this, although I don't seem to have ability to assign this to myself on this project.

**Comment by andrewvanbreda** [comment]
Hi @IanMiddlebrook,

I am trying to look at this for you
I have tried masquerading as your account, as well as a couple of Branch Coordinators, however I have not seen any sites displayed in italics for anyone at all.
I wonder if this is not working and it is the "Use cached data" option that is returning them for you.
Unfortunately I still don't have my full database access, so I can only partially access the data.
This means I can't search for confidential sites to check. Would you be able to email me some confidential sites names please, and also the usernames of a couple of branch managers that you know are working ok.

Thanks

Andy

**Comment by IanMiddlebrook** [comment]
Hi @andrewvanbreda 

A couple of sites in Hampshire will serve as a good example - ... [deleted] ...

I can see these if I masquerade as 'Hampshire UKBMS' and load up Branch Data on the Annual Summary page. They don't appear in italics in this list, though I don't remember if that was ever the case for Branch Co-ordinators? 
In my own account as Admin, I can load up the full data set, but these site do not appear in my drop down list, so I can't look at their summary tables. Previously, all confidential sites appeared in my list in italics.
Thankfully, the data are included in the Samples/Occurrences downloads.

If a normal User loaded up the Full Data Set, then these sites should not appear on the drop down list.
I think I'm just seeing the same list as a normal user.

Hope that helps, Ian

**Comment by andrewvanbreda** [comment]
Hi @IanMiddlebrook ,

Yes that has been really helpful.
I can see the line of code causing the problem. However I cannot just change it as it is not clear to me the reasoning for the line, so am going to have to get Gary in on this. I can point him to the right place so hopefully that will save him some time.
I will send him an email.

@Gary-van-Breda 
The problem appears to be in report_calendar_summary_2, and I think was introduced when the changes were made to update the report_helper etc to match between EBMS/UKBMS.
I think the bug is in line 1312 of report_calendar_summary_2.php

This is being set for Ian
$locationListArgs['extraParams']['exclude_sensitive'] = 1;

I dare not change it as I don't understand why it is being set at that point (or whether the line is right and something else is wrong causing it to behave incorrectly)

I have this older multidev that doesn't seem to get the issue for comparison. In this case though, the code is very different and that line doesn't even exist.

https://avb-d10-brc-ukbms-d10.pantheonsite.io

Thanks

Andy

**Comment by Gary-van-Breda** [comment]
I agreed - I think was a consequence of the work on the AS page which aligned UKBMS and EBMS.

Code fix pushed through to Live.

I've taken out the sensitive check for Supermanagers only: nobody else should see sensitive sites that are not assigned to them directly.

@IanMiddlebrook : can you have a check to see if you are happy?

**Comment by IanMiddlebrook** [comment]
That's great - thanks @andrewvanbreda @Gary-van-Breda
