### ISSUE TITLE
Site Assignment - missing branches

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#44]
I just tried to make some assignments using the 'Site Assignment' feature, but noticed that 2 Butterfly Conservation Branches are missing from the drop down list: Suffolk and Surrey & SW London.

Could these branches please be added?

**Comment by Gary-van-Breda** [comment]
The Butterfly Conservation Branches are locations of type "Butterfly Conservation Branch" in the warehouse. In order to add these 2 missing branches to the drop down, location records must be inserted into the warehouse (warehouse1), and in order for the Site assignment to work, these records must have the correct boundary geometries.

**Comment by IanMiddlebrook** [comment]
Where did the boundaries for the other branches come from, and were these 2 branches not included?

**Comment by DavidRoy** [comment]
The original boundary shapefiles came from you Ian, but I am at a loss to explain why these missing branches have not been noticed before.  We'll schedule some time to reload the missing ones

**Comment by DavidRoy** [comment]
[SuffolkSurrey.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1176290/SuffolkSurrey.zip)

@BirenRathod - please load these two shapefiles as locations of Type = Butterfly Conservation Branch.  They should be public layers as they are used for both the UKBMS and iRecord.

**Comment by BirenRathod** [comment]
@DavidRoy , These layers have been added to live warehouse.

**Comment by IanMiddlebrook** [comment]
Thanks
