### ISSUE TITLE
Sample links on Raw Data table not showing with Firefox

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#54]
A branch co-ordinator is having trouble with the Raw Data tables on the Annual Summary page – apparently the sample links are not there in the dates. He has recently switched to using Firefox as a browser.

I have masqueraded as him, using Google Chrome, and there are no problems.

**Comment by Gary-van-Breda** [comment]
Which user is it?

**Comment by Gary-van-Breda** [comment]
Sorry - I've worked out that it is Bill Shreeves.
I've masqueraded as him using firefox and have no problems.
I have asked him for a screen dump.

**Comment by Gary-van-Breda** [comment]
Email sent to Bill:

Hello Bill,

Thanks for the screen dump. It has helped, as I can now explain.

There are restrictions on who gets to see the links on the Annual Summary page: as you can imagine we don’t want someone editing data from the other side of the country, even by accident. These restrictions are quite simple:
•	If you are looking at your own data, you can see the links.
•	If you are looking at your branch data, you can see the links.
•	If you are a super manager, or an administrator user, then you can see the links for all data.
•	Otherwise you can not see the links.

For performance reasons, the way of determining the nature of the data you are looking at is also simplistic: it is done by looking at the “Filter by Recorder” field. This has a downside as you have discovered: you can look at the same location, but depending on the value of the “Filter by Recorder” field, you will either see the links or you won’t.

For you (who are not a super manager or an administrator), in order to see the links, you must set the “Filter by Recorder” to “Branch Data” in order to see all the links for everyone who has recorded at a site (assuming you are allocated that site as a Branch Manager).

As an aside, there should be a message at the top of the raw data grid which informs users of this. I will investigate why this is not being displayed.

I hope this provides a satisfactory workaround for you.

I will inform Ian Middlebrook and David Roy.

Regards
Gary

**Comment by IanMiddlebrook** [comment]
Thanks Gary

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon : Can you unzip and deploy the following file into the UKBMS website? Thanks
[report_helper.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1311392/report_helper.zip)

This change should display the message telling normal/branch users that they need to set the Filter by User field as appropriate to get access to the links.

**Comment by BirenRathod** [comment]
Uploaded on ukbms/mydata website.

**Comment by Gary-van-Breda** [comment]
Message now displayed. Close?

**Comment by IanMiddlebrook** [comment]
Thanks Gary
