### ISSUE TITLE
Problem with sites listed in site assignment

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#72]
Hi some of the BC WCBS squares listed in the sites are not in the list of squares under the site assignment. For example East Scotland:

NT6565
NT7568
NT2515
NT2764
NT2710
NT8544
NT0923
NT5156
NT9263
NT5646
NT2856
NT3257
NT1174
NT4164
NT6027
NT6849
NT7352

The same is true for these squares:

SJ7488 | Cheshire and Peak
SJ7891 | Cheshire and Peak
SJ8487 | Cheshire and Peak
SJ7890 | Cheshire and Peak
SK2672 | East Midlands
SK1978 | East Midlands
NR4667 | Glasgow & SW Scotland
NM8441 | Glasgow & SW Scotland
NS4036 | Glasgow & SW Scotland
NM4454 | Glasgow & SW Scotland
NS8996 | Glasgow & SW Scotland
SC2273 | Isle of Man
SC4293 | Isle of Man
SC3572 | Isle of Man
SC3884 | Isle of Man
SC3887 | Isle of Man
SC3274 | Isle of Man
SC3688 | Isle of Man
SC2981 | Isle of Man
SC3978 | Isle of Man
NX4601 | Isle of Man
SC2866 | Isle of Man
SC3981 | Isle of Man
SC3583 | Isle of Man
SC3784 | Isle of Man
SC4298 | Isle of Man
NX4200 | Isle of Man
SC3699 | Isle of Man
SC4492 | Isle of Man
SC3786 | Isle of Man
SC3890 | Isle of Man
SC2972 | Isle of Man
SH4179 | North Wales
SH4574 | North Wales
SH2578 | North Wales
SH3589 | North Wales
SH3964 | North Wales

Please can this issue be investigated. Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
The problem is the defined borders of the Butterfly Conservation Branches (BCB): these are stored as shapes in the database, and the site assignment works out which BCB a square is in when the filter is used.

There is a massive section of east of Scotland (from the Forth down to the border) that is not part of a BCB, and certainly not part of the East of Scotland BCB.

It also looks like the boundaries only include mainland UK/Northern Ireland - there seem to be no islands included - none of the Scottish Islands are covered, nor is the Isle of Man, Anglesey / Holyhead (the North Wales ones), not even the Isle of Wight is covered by "Hampshire and Isle of Wight"!

Other issues not covered by the above:
SJ7488 | Cheshire and Peak : In Lancashire BCB
SJ7891 | Cheshire and Peak : In Lancashire BCB
SJ8487 | Cheshire and Peak : In Lancashire BCB
SJ7890 | Cheshire and Peak : In Lancashire BCB
SK2672 | East Midlands : In Cheshire and Peak BCB
SK1978 | East Midlands : In Cheshire and Peak BCB
NS4036 | Glasgow & SW Scotland : This is OK. Shows up in search
NS8996 | Glasgow & SW Scotland : In East Scotland BCB

The BCB records need to be updated to include the Islands and missing chunk of Scotland.

In the meantime, all the island squares are still there, but have a "null" for the Branch. Remove the filter for the Branch - choose the "<Please select Butterfly Conservation Branch>" option. This will give a full list in the sites drop down - it will take a few seconds to populate. You can then the pick the square from this complete list.

**Comment by zrandle** [comment]
@Gary-van-Breda I'll give it a go. Thank you Zoe

**Comment by zrandle** [comment]
@Gary-van-Breda @DavidRoy  What is the origin of the Branch Boundary shape file you are using? I have one that may be better but Github wont let me attach it here. I will email it to you.

**Comment by Gary-van-Breda** [comment]
I don't know where these come from, I don't think I did it. All I can tell is that they were uploaded on 2013-04-03.

**Comment by zrandle** [comment]
@DavidRoy can you shed any light on the origins of the Branch Boundary Shape File?

**Comment by DavidRoy** [comment]
Boundaries were supplied by BC when the site initially setup.  If BC can supply a new shapefile we can update the system accordingly.  I suggest a new issue is raised for reloading the boundaries.
