### ISSUE TITLE
Upload new 2016 squares

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#8]

**Comment by zrandle** [comment]
Hi 
Please can the newly selected squares (2016) be uploaded to the system soon?

Thanks 

Zoe

**Comment by DavidRoy** [comment]
[WCBS sqs to add to online system.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/790637/WCBS.sqs.to.add.to.online.system.xlsx)

File containing locations of 1km WCBS squares to load into the Warehouse.

Note there are three sheets.
BC - to assign to Survey = UKBMS WCBS-BC (id = 306)
BBS - to assign to Survey = UKBMS WCBS-BBS (id = 305)
NT - to assign to Survey = UKBMS WCBS-BC (id = 306)

On upload, 1km squares should be automatically assigned to their relevant location = 'Butterfly Conservation Branch' so that they then appear in Branch reports

**Comment by zrandle** [comment]
My top priority. Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
I have the squares now ready to be uploaded. I am assuming 10 sections each, which will be initialised to be squares forming a diagonal from the bottom left corner to the top right of the site in question.
The allocation to branches is done via branch managers, in a very similar way to sites being assigned to users, rather than to a location. Which branch manager users should these be assigned to?

**Comment by DavidRoy** [comment]
Thanks.  Yes - 10 sections.

Can the branch allocation be done based on the spatial intersection between the 1km grid square and location_type = 'Butterfly Conservation Branch'.  For 1km squares intersecting with more than one branch they should be assigned to branch with the largest area of intersection (preferable) or 1km grid square centroid (if much simpler to implement).

**Comment by Gary-van-Breda** [comment]
Yes I can base the branch allocation on the intersection, but I need the branch manager users: which branch managers equate to which branches?

**Comment by Gary-van-Breda** [comment]
Locations uploaded into warehouse: not currently allocated to any branch managers (see comment above).

**Comment by DavidRoy** [comment]
Is an option to deploy the 'transects-allocation' (i.e. as is available on eBMS) form to the UKBMS to enable this allocation to be done more efficiently?   If so, we should generate a new issue for this and an estimate of the work (time) required to do this

**Comment by Gary-van-Breda** [comment]
Yes that is the best option.
For the D7 site, configuration will take 15minutes.
For the D6, some testing will be required, estimate 1hour.

**Comment by DavidRoy** [comment]
Thanks.  Only needed for the D7 site as we are moving over soon

**Comment by zrandle** [comment]
Hi Gary Branch Champion info for you. [Branch Champs for Gary.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/864861/Branch.Champs.for.Gary.xlsx)

**Comment by DavidRoy** [comment]
@zrandle.  There is not resource to do this automatically but there is a report (initially developed for Luxembourg BMS, now used for eBMS) available that makes this much quicker to do (by you and Ian).  Let's review once Gary has implemented the report.

**Comment by Gary-van-Breda** [comment]
Form now deployed and configured on D7 site (Site Allocation menu option)

**Comment by DavidRoy** [comment]
I may have misunderstood the form, but the use case requirement for this form is to use tick boxes to allocate a branch manager to all the unallocated sites within his branch boundary.  An example as follows.
1. Select Allocation Type = 'Branch Manager (WCBS-BBS)
2. Butterfly Conservation Branch = 'Dorset'
3. Click Search which should return all WCBS-BBS sites in Dorset Branch
4. The select all and assign to a user

Otherwise, is the form aimed at querying existing allocations only?

**Comment by Gary-van-Breda** [comment]
There are 2 modes of operation for the form:

Mode 1:
In order to allocate all the locations to a particular user (e.g. as a branch manager), the steps would be as follows:

1. Select Allocation Type = 'Branch Manager (WCBS-BBS)
2. Butterfly Conservation Branch = 'Dorset'
3. Leave the site unselected
4. User = required user
5. Click Search: this will return a list of **all** the sites within the boundaries of the Branch. The checkboxes will indicate whether the user is currently allocated to the site or not.
6. Press one of: "Select all" to assign all the sites to the user; "Deselect all" to remove the assignments; click the individual checkboxes to (de)assign as appropriate.

Mode 2:
In order to check/set all the allocations for a particular site, the steps would be as follows:

1. Select Allocation Type = 'Branch Manager (WCBS-BBS)
2. Butterfly Conservation Branch = 'Dorset'
3. Site = required site
4. Leave User unselected
5. Click Search: this will return a list of **all** the users for that site. The checkboxes will indicate whether any individual user is currently allocated to the site or not.
6. The "Select all" and "Deselect all" buttons are not available in this mode. Click the individual checkboxes to (de)assign as appropriate.

**Comment by DavidRoy** [comment]
@zrandle @IanMiddlebrook Without further development funds, this is the only immediate improvement we can provide on allocating users to sites and branches.  Can you add a new issue for future requirements to improve efficiency for this task.

**Comment by zrandle** [comment]
Please can this be explained more clearly. Is this automated? If not how do I allocate squares to branch managers using the above steps?

**Comment by DavidRoy** [comment]
Not fully automated but should be quick to do.

Here are the instructions.
1. Login to the test version of the ukbms/mydata site at http://test.brc.ac.uk/ukbms/mydata/
2. Goto menu item 'Site Assignment'. http://test.brc.ac.uk/ukbms/mydata/branch-assignment
3. Follow Gary's instructions above.  Mode 1 should be quite an efficient way of allocating sites to a branch champion

Give it a go and let me know.  Note that is only deals with BC Branch allocations currently as we don't have the BBS region boundaries loaded in the system

**Comment by zrandle** [comment]
OK, I'll give it a go. As for the BBS squares they can be allocated using the BC Branch boundaries too. The BC champions want access to the BBS butterfly data. Thanks

**Comment by zrandle** [comment]
hi it sort of works but has frozen! In addition to this I couldn't find Clare Topping (Branch Manager for Beds and Northants) on the list. She is registered and assigned as Branch manager...

**Comment by IanMiddlebrook** [comment]
Username:  ClareT



[cid:image001.jpg@01D2BEA9.6C394A10]

Ian Middlebrook Butterfly Monitoring Co-ordinator

Email: imiddlebrook@butterfly-conservation.org  Direct line: 01929 406032

Butterfly Conservation, Manor Yard, East Lulworth, Wareham, Dorset BH20 5QP  Tel: 01929 400209

Company limited by guarantee, registered in England (2206468). Charity registered in England and Wales (254937) and in Scotland (SCO39268).

www.butterfly-conservation.org<http://www.butterfly-conservation.org/>

[cid:image002.png@01D2BEA9.6C394A10]<https://www.facebook.com/savebutterflies/>

[cid:image003.jpg@01D2BEA9.6C394A10]<https://twitter.com/savebutterflies>

Follow me on Twitter @UKBMSLive




The views and comments expressed in this email do not necessarily express the views of Butterfly Conservation.
Our promise to you: We will never swap, sell or rent your details to anyone and we will always follow the strict code of conduct set out by the Fundraising Regulator.

**Comment by zrandle** [comment]
There is an issue with this. It times out and several Branch managers are missing from the user list...

**Comment by Gary-van-Breda** [comment]
OK I'll have a look at the time out. Please note that this is a test system: this points at a different warehouse and the user list is as was on the live site a while back.

**Comment by DavidRoy** [comment]
Also, which point does it time out?  It worked ok for me

**Comment by zrandle** [comment]
when you do step 6 of the instructions: 6.	Press one of: "Select all" to assign all the sites to the user;

**Comment by zrandle** [comment]
OK, so this partially worked...  all sites for Dorset were selected for me to be branch manager, but then nothing happens and the allocation hasn't stuck... This would be a great solution if it worked!

**Comment by DavidRoy** [comment]
@Gary-van-Breda anything you can do on the performance of this page?  Or should we review once the site is on live (and hopefully performing faster)?

**Comment by Gary-van-Breda** [comment]
Firstly there is a bug on the page: its not accessing the warehouse correctly, hence the allocation failure to stick seen by Zoe. I'm investigating. It may be that this will affect the performance, so its probably best to wait until I've sorted that.

**Comment by zrandle** [comment]
OK thanks, I await further instruction!

**Comment by Gary-van-Breda** [comment]
Zoe, can you check whether this now works for you?

**Comment by zrandle** [comment]
Yes it does thank you
